version: '3.8'
name: armazenamento-documento

services:
  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: always
    env_file:
      - mysql/.env
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
